#!/usr/bin/env bash

script_dir=$(dirname "$BASH_SOURCE")

cd "$script_dir"

sudo add-apt-repository -y ppa:deadsnakes/ppa
sudo apt update -y
sudo apt install -y python3.8

rm -rf venv

virtualenv --python=python3.8 venv
source venv/bin/activate

pip install \
    --upgrade \
    --upgrade-strategy \
    eager \
    --no-index \
    --find-links packages \
    packages/pip-21.2.4-py3-none-any.whl

time pip install \
    --upgrade \
    --upgrade-strategy \
    eager \
    --no-index \
    --find-links packages \
    flake8 \
    lazy_object_proxy \
    anyio \
    chevron \
    responses \
    types_paramiko \
    wheel \
    yarl \
    oyaml \
    pyotp \
    uvicorn \
    deepdiff \
    certifi \
    ecdsa \
    typing_extensions \
    websocket_client \
    psycopg2 \
    pynacl \
    aioitertools \
    ipython_genutils \
    types_requests \
    docutils \
    pyjwt \
    pyyaml \
    arrow \
    factory_boy \
    pygments \
    slack_sdk \
    colorlog \
    requests_toolbelt \
    keyring \
    asyncpg \
    docker \
    zeep \
    typed_ast \
    cffi \
    alembic \
    setuptools \
    bsrp \
    aiohttp \
    tornado \
    werkzeug \
    pytest_cov \
    entrypoints \
    lark-parser \
    pycparser \
    filelock \
    fastjsonschema \
    psycopg2_binary \
    execnet \
    defusedxml \
    lazy-object-proxy \
    toml \
    aws_xray_sdk \
    click \
    daemonize \
    importlib_metadata \
    wrapt \
    spindrift \
    sqlalchemy_utils \
    python_jose \
    ipdb \
    pytest_forked \
    platformdirs \
    xmltodict \
    distro \
    backcall \
    xmlsec \
    pep517 \
    dos \
    oauthlib \
    mangum \
    isort \
    jsonschema \
    pycrypto \
    deprecated \
    jdcal \
    secretstorage \
    dynamodb_json \
    psycopg2_binary \
    ldap3 \
    numpy \
    asn1crypto \
    gitignore_parser \
    pip \
    pyrsistent \
    aws_lambda_powertools \
    httpx \
    python_slugify \
    constrictor \
    websockets \
    mccabe \
    starlette \
    markupsafe \
    python_dateutil \
    sqlalchemy_redshift \
    pluggy \
    tomlkit \
    cfgv \
    autopep8 \
    requests_file \
    types_ipaddress \
    flake8-colors \
    chardet \
    pytz \
    simplejson \
    requests \
    lxml \
    botocore \
    pyee \
    pexpect \
    typing_extensions \
    pbr \
    jsonpickle \
    faker \
    typed_ast \
    six \
    pyrsistent \
    serverlessrepo \
    marshmallow \
    bcrypt \
    pylint \
    geoalchemy2 \
    cryptography \
    coverage \
    types_python_slugify \
    pytest \
    text_unidecode \
    unidecode \
    more_itertools \
    s3transfer \
    pgpy \
    boto3 \
    geopy \
    multidict \
    yarl \
    pytest_postgresql \
    pycodestyle \
    jinja2 \
    multidict \
    pkgconfig \
    pydantic \
    requests_oauthlib \
    atomicwrites \
    mako \
    lxml \
    playwright \
    setuptools_scm \
    msgpack \
    colorama \
    astroid \
    aiobotocore \
    pynacl \
    psycopg2_binary \
    greenlet \
    decorator \
    cffi \
    pyzmq \
    jmespath \
    xmlsec \
    pyhcl \
    appnope \
    locald \
    idna \
    build \
    identify \
    types_enum34 \
    pyzmq \
    h11 \
    inflection \
    pyasn1 \
    tomli \
    python_jwt \
    overpunch \
    pytest_asyncio \
    typing_extensions \
    packaging \
    ply \
    async_timeout \
    fastapi \
    wcwidth \
    isodate \
    pyflakes \
    attrs \
    cffi \
    itsdangerous \
    dataclasses \
    mypy_extensions \
    openpyxl \
    paramiko \
    jeepney \
    slack_bolt \
    mirakuru \
    pillow \
    markupsafe \
    urllib3 \
    jira \
    et_xmlfile \
    mypy \
    flake8-quotes \
    networkx \
    pytest_xdist \
    bcrypt \
    sodapy \
    selenium \
    iniconfig \
    python_editor \
    ntplib \
    terroir \
    types_chardet \
    ordered-set \
    ptyprocess \
    py \
    lockfile \
    passlib \
    httpcore \
    python_dotenv \
    psutil \
    sniffio \
    sqlalchemy \
    idna-ssl \
    flask \
    apispec \
    psycopg2_binary \
    pygithub \
    cryptography \
    numpy \
    markupsafe \
    enctempfile \
    geographiclib \
    greenlet \
    types_cryptography \
    rfc3986 \
    cached_property \
    coverage \
    python-hcl2 \
    aws-requests-auth \
    pyparsing \
    authlib \
    pyyaml \
    zipp \
    port_for \
    charset_normalizer \
    jwcrypto \
    psycopg2_binary \
    future \
    aws_lambda_builders \
    ipython \
    jedi \
    appdirs
